[package]
name = "iir_blur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
halide = {path = "../../"}
[dependencies]
halide = {path = "../../"}
image = "0.24.1"
